dataset:
  dataset_path: /home/randellini/action_recognizer/dataset/augmented_square_256_mp4
  path_dataset_train_csv: /home/randellini/action_recognizer/dataset/augmented_square_256_mp4/df_train.csv
  path_dataset_val_csv: /home/randellini/action_recognizer/dataset/augmented_square_256_mp4/df_val.csv
  batch_size: 8
  class_to_recognize: screw_allenkey_1
model:
  name_time_model: timesformer # timesformer - r2plus1d_18 - r3d - 3d_slowfast
  init_dim: 768 # 768 for timesformer - 512 for r2plus1d_18 - 2048 for r3d - 2304 for 3d_slowfast
  num_autoencoder_layers: 2 # 2 or 3
  dim_autoencoder_layers: 256,128 #512,256,128
  freeze_layers: 1
  epoch_start_unfreeze: 10
  layer_start_unfreeze: 0 # dal layer 6 al 10
  saving_dir_experiments: results/timesformer/avvita_brugola_1
  saving_dir_model: v2
  num_epoch: 50
  learning_rate: 0.005
  scheduler_type: MultiStepLR
  milestones: [5,10,25,50]
  use_pretrained_scheduler: 1
  lr_factor: 0.1
  dropout: 0.3
  do_train: 1
  do_test: 1
data:
  num_frames_to_sample: 32 # 64 non ce la fa nella macchina con 12 GB
  mean: [0.45, 0.45, 0.45]
  std: [0.225, 0.225, 0.225]
  resize_to: 224
  permute_color_frame: 1 # 1 for timesformer - 0 for r2plus1d_18 - 0 for r3d - 0 for 3d_slowfast
  alpha_slowfast: 4
